Shared and Auth modules angular
CogniBuild/Campus.Master pull request #55
Opened 2020-12-11 16:35 UTC by profileEnumerable

2020-12-11 18:02 UTC, antonAce requested changes
Thank you for this major clean-up! There are some extra suggestions

2020-12-14 12:54 UTC, profileEnumerable commented on Src/Campus.Master.API/UI/src/app/auth/sing-in/sing-in.component.html
> +        <img src="../../../assets/img/sign-in/signIn.png" alt="photo"/>
reduced

2020-12-14 12:55 UTC, profileEnumerable commented on Src/Campus.Master.API/UI/src/app/auth/registration-page/registration-page.component.html
> +        <img src="../../../assets/img/registration/reg.png" alt="photo">
reduced

2020-12-14 13:44 UTC, profileEnumerable commented on Src/Campus.Master.API/UI/src/app/auth/shared/services/sign-in.service.ts
> +import { StateTransfer } from '../../../models/state-transfer';
reduced

2020-12-14 13:57 UTC, profileEnumerable commented on Src/Campus.Master.API/UI/src/app/data/dao/impl/CategoryDAOArray.ts
> +import { Project } from '../../../models/task-list/project';
fixed

2020-12-14 13:57 UTC, profileEnumerable commented on Src/Campus.Master.API/UI/src/app/data/dao/impl/TaskDAOArray.ts
> +import { Task } from 'src/app/models/task-list/task';
fixed

2020-12-14 15:40 UTC, profileEnumerable commented on Src/Campus.Master.API/UI/src/app/auth/sing-in/sing-in.component.sass
> +@import "../../../styles/styles"
fixed

2020-12-14 15:50 UTC, profileEnumerable commented on Src/Campus.Master.API/UI/src/app/dialog/edit-task-dialog/edit-task-dialog.component.ts
> +import { DataHandlerService } from '../../services/data-handler.service';
fixed

2020-12-14 15:58 UTC, antonAce commented on Src/Campus.Master.API/UI/src/app/auth/shared/services/registration.service.ts
> +import { StateTransfer } from '../../../models/state-transfer';
Just add `@sharedModels` for other references

2020-12-14 16:45 UTC, antonAce approved these changes
Thanks for the major clean-up :shipit:

2020-12-14 17:03 UTC, merged